### PR TITLE
Added colors, year updates, and state selection table to scatterplot

### PR DESCRIPTION
**Pull request by mackliet**

### CODE REVIEW

**Comment by reillykw** [comment]
Could use a better color scheme maybe?

**Review by reillykw — APPROVED** [review]
Color scheme seems off.  I don't know, maybe just clashes with the heat map.  
The overall pattern is great, nice work on the selection fields.  Kinda helped parse through the data a little bit more. 
The naming case conventions are wrong, should use camelCase for properties and fields and PascalCase for class names.  No snake_case. Just a typescript convention. 
The "centered" class on your div is causing some issues withthe placement of the table.  When removed it places right, but moves your selection field over a bit.

**Comment by mackliet** [comment]
Color scheme can be changed pretty easy. I chose this one because of the default d3 color schemes it was the easiest to read in the selection table. What do you think the color scheme should be like?

I can change how the table is placed in next PR.

Sigh...I just hate camel case haha. I'll change it next PR

**Comment by reillykw** [comment]
I don't know what the color scheme should be like, we can discuss that down the road.  Just saw the year integration, so that's really awesome! We need some way to link selected states with the dots on your table better. 

I come from a python background mostly, and I disliked camel case for the longest time.  I really liked snake_case and PascalCase for classes.  But when it comes to language conformity, I think I've grown more accustom to using the standards that developed in the communities.  

My least favorite I think is Golang.  To export a type outside of a given code file, the name of the type must start with a Capital letter.  I don't like that! It is what it is and I think it's best to try and keep the case standard tidy here.

**Pull request merged**
